name: 'fleetio_analytics'
version: '1.0.0'
profile: 'fleetio_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  fleetio_analytics:
    +schema: raw        # Seeds go to main_raw, replacement for 1_raw
    +quote_columns: false

models:
  fleetio_analytics:
    2_staging:
      +schema: staging
      +materialized: view
    3_base:
      +schema: base
      +materialized: table
    4_intermediate:
      +schema: intermediate
      +materialized: view
    5_mart:
      +schema: mart
      +materialized: table